### PR TITLE
Trying to build windows better

### PR DESCRIPTION
**Pull request by muschellij2**
I'm messing around with the flags (only on windows) to try to get the compiler flags to match up so that we can identify problems that are due to compiler problems that are not due to flags.

### CODE REVIEW

**Comment by muschellij2** [comment]
Are you comfortable with this change in ITK @stnava ?

**Comment by stnava** [comment]
what change, specifically?

**Comment by muschellij2** [comment]
Most of these are just for windows I guess.  I'm getting errors with ANTsR with `__ZN3itk9TimeStampaSERKS0_` not found, but I thought it may be my ITK branch, but probably not.  Going to do fresh install again.

**Comment by muschellij2** [comment]
I've added a new ITK tag, which should help with https://github.com/ANTsX/ANTsRCore/issues/63 I believe.  I'm unsure about contributing to ITK main branch with PRs.  Have you been successful with this before @stnava ?

**Comment by stnava** [comment]
yes but it's slow.  the "fast" way to do it is through gerrit.  see the itk-dev documents.

**Pull request merged**
